### PR TITLE
Issue #1254: fix function "reset to factory defaults" for robots with arduinoAgentOrToken connection.

### LINKED ISSUE #1254: Function "reset to factory defaults" doesn't work for some robots with create agent programs
When using robots having factory default programs, the option "reset to factory defaults" doesn't program the robot when the robot is connected through create agent programs ([BobDude](https://www.bob3.org/de/details/software), for instance).

There is no error message, instead the message *Your program »**robot's initial program name**« will run in a moment!* is shown, but nothing is pushed to the robot.

Reset program is pushed as expected when the robot is connected to the server with the OpenRobertaConnector program, so probable cause lies within logic for resetting when robot is connected through create agent programs. 

## TODOs
- Identify which robots are affected.
  Robots having `robot.connection = arduinoAgentOrToken` **and** `robot.factory.default = <defined>`:
  - Bob3
  - Rob3rta
- Check if reset/transfer worker(s) need to be updated.
  - Bob3 and Rob3rta both use `Bob3TransferWorker` for transferring the program.
- Check if run workflow works as expected with create agent programs.

## TESTs
- Factory default should be pushed to the robot, irrespective of the type of connection to the server, wherever applicable.

### PR DESCRIPTION
**Pull request by RaghuvirShirodkar**
# Description

This PR implements the following changes:

- update Bob3TransferWorker to get encoded hex of the factory default program for reset requests.
- update progRun.controller::reset2DefaultFirmware() to transfer program for arduinoAgentOrToken connection robots.

Fixes #1254 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Tested on affected NIBO robots (Bob3, Rob3rta).

For each robot:
- Connected robot to computer.
- Clicked on "reset to factory defaults".
- Checked whether robot is programmed as expected.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: RobotArdu/src/main/java/de/fhg/iais/roberta/worker/transfer/Bob3TransferWorker.java [hunk 1]
```diff
@@ -2,13 +2,21 @@
...
+        // Check whether a reset is requested. If yes, get the base64 encoded hex of the factory default program.
+        if ( project.getResult() == Key.FIRMWARE_RESET_SUCCESS ) {
+            String path = project.getRobotFactory().getPluginProperties().getCompilerResourceDir() + project.getCompiledProgramPath() +
+                "." + project.getBinaryFileExtension();
+            project.setCompiledHex(Util.getBase64EncodedHex(path, NIBOHexPrefix.getHexPrefixForRobot(project.getRobot())));
+        }
+        // Check whether the robot is connected with create agent program...
         if ( project.getRobotCommunicator().getState(project.getToken()) == null ) {
             project.setResult(Key.ROBOT_PUSH_RUN);
         } else { // otherwise it uses Connector Program
```
Comment (bjost2s) [inline RobotArdu/src/main/java/de/fhg/iais/roberta/worker/transfer/Bob3TransferWorker.java:22]: As we already have a dedicated workflow for "reset" and a "resetFirmware" worker, why not introducing a "transferFirmware" worker

Comment (RaghuvirShirodkar) [reply RobotArdu/src/main/java/de/fhg/iais/roberta/worker/transfer/Bob3TransferWorker.java:16]: Added `NIBOResetFirmwareWorker` instead.
